CREATE TABLE IF NOT EXISTS buffer_paypal_notification (
	id uuid NOT NULL PRIMARY KEY,
	create_time timestamp NOT NULL,
	txn_type varchar(500) NULL,
	subscr_id varchar(500) NULL,
	last_name varchar(500) NULL,
	residence_country varchar(500) NULL,
	mc_currency varchar(500) NULL,
	item_name varchar(500) NULL,
	amount1 varchar(500) NULL,
	business varchar(500) NULL,
	amount3 varchar(500) NULL,
	recurring varchar(500) NULL,
	verify_sign varchar(500) NULL,
	payer_status varchar(500) NULL,
	test_ipn varchar(500) NULL,
	payer_email varchar(500) NULL,
	first_name varchar(500) NULL,
	receiver_email varchar(500) NULL,
	payer_id varchar(500) NULL,
	invoice varchar(500) NULL,
	reattempt varchar(500) NULL,
	item_number varchar(500) NULL,
	subscr_date varchar(500) NULL,
	charset varchar(500) NULL,
	notify_version varchar(500) NULL,
	period1 varchar(500) NULL,
	mc_amount1 varchar(500) NULL,
	period3 varchar(500) NULL,
	mc_amount3 varchar(500) NULL,
	ipn_track_id varchar(500) NULL,
	transaction_subject varchar(500) NULL,
	payment_date varchar(500) NULL,
	payment_gross varchar(500) NULL,
	payment_type varchar(500) NULL,
	txn_id varchar(500) NULL,
	receiver_id varchar(500) NULL,
	payment_status varchar(500) NULL,
	payment_fee varchar(500) NULL,
	sync_reservation_id uuid NULL,
	sync_reservation_time timestamp NULL,
	sync_reservation_times int NULL,
	sync_start_time timestamp NULL,
	sync_end_time timestamp NULL,
	sync_result varchar(8000) NULL
);

CREATE TABLE IF NOT EXISTS invoice (
	id uuid NOT NULL PRIMARY KEY,
	create_time timestamp NOT NULL,
	id_account uuid NOT NULL REFERENCES account(id),
	billing_period_from date NULL,
	billing_period_to date NULL,
	id_buffer_paypal_notification uuid NULL REFERENCES buffer_paypal_notification(id),
	"status" int NULL,
	paypal_url varchar(8000) NULL,
	automatic_billing boolean NULL,
	subscr_id varchar(500) NULL,
	disabled_for_trial boolean NULL,
	disabled_for_add_remove_items boolean NULL,
	id_previous_invoice uuid NULL REFERENCES invoice(id),
	delete_time timestamp NULL
);

CREATE TABLE IF NOT EXISTS invoice_item (
	id uuid NOT NULL PRIMARY KEY,
	id_invoice uuid NOT NULL REFERENCES invoice(id),
	product_code varchar(5) NOT NULL,
	unit_price numeric(18, 4) NOT NULL,
	units numeric(18, 4) NOT NULL,
	amount numeric(18, 4) NOT NULL,
	detail varchar(500) NOT NULL,
	item_number varchar(500) NULL,
	description varchar(500) NULL,
	create_time timestamp NULL
);

CREATE TABLE IF NOT EXISTS movement (
	id uuid NOT NULL PRIMARY KEY,
	id_account uuid NOT NULL REFERENCES account(id),
	create_time timestamp NOT NULL,
	type int NOT NULL,
	id_user_creator uuid NULL REFERENCES "user"(id),
	description text NULL,
	paypal1_amount numeric(22, 8) NOT NULL, -- transactions must be operated with double of precision (8 digits) stored on other tables (4 digits)
	bonus_amount numeric(22, 8) NOT NULL, -- transactions must be operated with double of precision (8 digits) stored on other tables (4 digits)
	amount numeric(22, 8) NOT NULL, -- transactions must be operated with double of precision (8 digits) stored on other tables (4 digits)
	credits bigint NOT NULL,
	profits_amount numeric(22, 8) NOT NULL,
	id_invoice_item uuid NULL REFERENCES invoice_item(id),
	product_code varchar(500) NOT NULL,
	expiration_time timestamp NULL,
	expiration_start_time timestamp NULL,
	expiration_end_time timestamp NULL,
	expiration_tries int NULL,
	expiration_description varchar(500) NULL,
	expiration_on_next_payment boolean NULL,
	expiration_lead_period varchar(500) NULL,
	expiration_lead_units int NULL,
	give_away_negative_credits boolean NULL
);

CREATE TABLE IF NOT EXISTS subscription (
	id uuid NOT NULL PRIMARY KEY,
	id_buffer_paypal_notification uuid NULL REFERENCES buffer_paypal_notification(id),
	create_time timestamp NOT NULL,
	id_account uuid NULL REFERENCES account(id),
	active boolean NOT NULL,
	subscr_id varchar(500) NULL,
	last_name varchar(500) NULL,
	residence_country varchar(500) NULL,
	mc_currency varchar(500) NULL,
	amount1 varchar(500) NULL,
	business varchar(500) NULL,
	amount3 varchar(500) NULL,
	recurring varchar(500) NULL,
	verify_sign varchar(500) NULL,
	payer_status varchar(500) NULL,
	test_ipn varchar(500) NULL,
	payer_email varchar(500) NULL,
	first_name varchar(500) NULL,
	receiver_email varchar(500) NULL,
	payer_id varchar(500) NULL,
	invoice varchar(500) NULL,
	reattempt varchar(500) NULL,
	subscr_date varchar(500) NULL,
	charset varchar(500) NULL,
	notify_version varchar(500) NULL,
	period1 varchar(500) NULL,
	mc_amount1 varchar(500) NULL,
	period3 varchar(500) NULL,
	mc_amount3 varchar(500) NULL,
	ipn_track_id varchar(500) NULL,
	stat_cencelation_notification_time timestamp NULL,
	stat_creation_notification_time timestamp NULL
);
